In [1]:
import numpy as np
import pandas as pd

In [40]:
class perceptron:
    def __init__(self,eta,epochs):
        self.weights=np.random.rand(3) * 1e-4
        print(f"self.weights :{self.weights}")
        self.eta=eta
        self.epochs=epochs
        
    def activationFunction(self,inputs,weights):
        z=np.dot(inputs,weights)
        return np.where(z>0,1,0)
    
    def fit(self,X,y):
        self.X=X
        self.y=y
        
        X_with_bias=np.c_[self.X,np.ones((len(self.X),1))]
        print(f"X_with_bias : \n{X_with_bias}")
        
        for epochs in range(self.epochs):
            print(f"for epoch: {epochs}")
            y_hat=self.activationFunction(X_with_bias,self.weights)
            print(f"predicted value: \n {y_hat}")
            error=self.y - y_hat
            print(f"error: \n {error}")
            self.weights= self.weights+self.eta*np.dot(X_with_bias.T,error)
            print(f"updated_weigths: \n {self.weights}")
            
    def predict(self,X):
        X_with_bias=np.c_[X,np.ones((len(self.X),1))]
        return self.activationFunction(X_with_bias,self.weights)
        
        
                 

AND OPERATION

In [37]:
data={"x1":[1,0,1,0],"x2":[0,0,1,1],"y":[0,0,1,0]}
AND=pd.DataFrame(data)
AND

x1  x2  y
0   1   0  0
1   0   0  0
2   1   1  1
3   0   1  0

In [22]:
X=AND.drop("y",axis=1)

In [23]:
X

x1  x2
0   1   0
1   0   0
2   1   1
3   0   1

In [25]:
y=AND["y"]
y.to_frame()

y
0  0
1  0
2  1
3  0

In [41]:
model=perceptron(eta=0.5,epochs=5)
model.fit(X,y)

self.weights :[7.95752269e-05 9.43292172e-05 9.42070534e-05]
X_with_bias : 
[[1. 0. 1.]
 [0. 0. 1.]
 [1. 1. 1.]
 [0. 1. 1.]]
for epoch: 0
predicted value: 
 [1 1 1 1]
error: 
 0   -1
1   -1
2    0
3   -1
Name: y, dtype: int64
updated_weigths: 
 [-0.49992042 -0.49990567 -1.49990579]
for epoch: 1
predicted value: 
 [0 0 0 0]
error: 
 0    0
1    0
2    1
3    0
Name: y, dtype: int64
updated_weigths: 
 [ 7.95752269e-05  9.43292172e-05 -9.99905793e-01]
for epoch: 2
predicted value: 
 [0 0 0 0]
error: 
 0    0
1    0
2    1
3    0
Name: y, dtype: int64
updated_weigths: 
 [ 0.50007958  0.50009433 -0.49990579]
for epoch: 3
predicted value: 
 [1 0 1 1]
error: 
 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated_weigths: 
 [ 7.95752269e-05  9.43292172e-05 -1.49990579e+00]
for epoch: 4
predicted value: 
 [0 0 0 0]
error: 
 0    0
1    0
2    1
3    0
Name: y, dtype: int64
updated_weigths: 
 [ 0.50007958  0.50009433 -0.99990579]


In [42]:
model.predict(X)

array([0, 0, 1, 0])